[package]
name = "entrypoint"
description = "opinionated application framework/wrapper that eliminates main function boilerplate"
version = "0.0.0"
edition = "2021"
license = "MIT"

homepage = "https://github.com/melloyawn/entrypoint"
repository = "https://github.com/melloyawn/entrypoint"

categories = [
    "command-line-interface",
    "config",
    "rust-patterns",
]

keywords = [
    "application",
    "boilerplate",
    "config",
    "entrypoint",
]

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
